import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchSubreddits} from '../../api/redditAPI';

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getSubs = createAsyncThunk(
    'subreddits/getSubs',
    async () => {
        const response = await fetchSubreddits();
        // The value we return becomes the `fulfilled` action payload
        return response;
    }
);


export const subredditsSlice = createSlice({
    name: 'subreddits',
    initialState: {
        subreddits: {},  // Objects keyed by sub id
        error: false,
        loading: false
    },
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(getSubs.pending, (state) => {
                state.loading = true;
                state.error = false;
            })
            .addCase(getSubs.fulfilled, (state, action) => {
                state.loading = false;
                const subreddits = action.payload // array of objects keyed by a number
                subreddits.map((subreddit) => {
                    const {id, title, thumbnail, preview, author, ups, num_comments, subreddit_name_prefixed} = subreddit.data
                    state.subreddits[id] = {
                        id: id,
                        title: title,
                        author: author,
                        preview: preview,
                        thumbnail: thumbnail,
                        upvotes: ups,
                        comments: num_comments,
                        subreddit: subreddit_name_prefixed
                    }
                })
            })
            .addCase(getSubs.rejected, (state) => {
                state.loading = false
                state.error = true
                state.subreddits = {}
            })
    },
});

export const { } = subredditsSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectSubreddits = (state) => state.subreddits.subreddits;
export const selectSubById = (id) => (state) => state.subreddits.subreddits[id]
export const selectLoading = (state) => state.subreddits.loading
export const selectError = (state) => state.subreddits.error


export default subredditsSlice.reducer;