import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchPosts, fetchDummyJson } from '../../api/redditAPI';

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchSubPosts = createAsyncThunk(
    'posts/fetchPosts',
    async (subreddit) => {
        const response = await fetchPosts(subreddit);
        // The value we return becomes the `fulfilled` action payload
        return response;
    }
);

export const fetchDummy = createAsyncThunk(
    'posts/fetchDummy',
    async () => {
        const response = await fetchDummyJson();
        // The value we return becomes the `fulfilled` action payload
        return response;
    }
);

export const postsSlice = createSlice({
    name: 'posts',
    initialState: {
        posts: {},
        error: false,
        loading: false
    },
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {

    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchSubPosts.pending, (state) => {
                state.loading = true;
                state.error = false;
            })
            .addCase(fetchSubPosts.fulfilled, (state, action) => {
                state.loading = false;
                const posts = action.payload // array of objects keyed by a number
                posts.map((post) => {
                    const {id, title, thumbnail, preview, author, ups, num_comments, subreddit_name_prefixed} = post.data
                    state.posts[id] = {
                        id: id,
                        title: title,
                        author: author,
                        preview: preview,
                        thumbnail: thumbnail,
                        upvotes: ups,
                        comments: num_comments,
                        subreddit: subreddit_name_prefixed
                    }
                })
            })
            .addCase(fetchSubPosts.rejected, (state) => {
                state.loading = false
                state.error = true
                state.data = {}
            })
            .addCase(fetchDummy.pending, (state) => {
                state.loading = true;
                state.error = false;
            })
            .addCase(fetchDummy.fulfilled, (state, action) => {
                state.loading = false;
                state.data = action.payload;
            })
            .addCase(fetchDummy.rejected, (state) => {
                state.loading = false
                state.error = true
                state.data = {}
            })
    },
});

export const { } = postsSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectPosts = (state) => state.posts.posts;
export const selectLoading = (state) => state.posts.loading


export default postsSlice.reducer;